services:
  emailservice:
    build: .
    ports:
      - "8080:5000"  # Map port 5000 in the container to port 8080 on your host
    env_file:
      - .envrc       # Include your environment variables from .envrc
    volumes:
      - ./path/to/host/folder:/root/.aspnet/DataProtection-Keys  # Persist keys outside the container
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection=Host=db;Port=5432;Database=EmailServiceDB;Username=postgres;Password=postgres123  # Use db service as host
    networks:
      - emailservice-net
    depends_on:
      - db  # Ensure db service is available before starting the emailservice

  db:
    image: postgres:13  # Use the official PostgreSQL image
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=EmailServiceDB
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist the database data
    networks:
      - emailservice-net

networks:
  emailservice-net:
    driver: bridge

volumes:
  postgres-data:
    driver: local
