name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on pushes to main branch

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Build and test
        run: dotnet test --configuration Release
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  continuous-delivery:
    name: Continuous Delivery
    needs: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/pagliaricci/be-challenge-sirius:latest
            ghcr.io/pagliaricci/be-challenge-sirius:${{ github.ref_name }}
